### ISSUE TITLE
Special characters not supported 

### ISSUE THREAD

**Issue by jessiemorin** [taufik-nurrohman/tag-picker#17]
Tried using it in my french project and characters like é,è,à,ï and other accents aren't supported. I wonder if there's a quick fix.
Thanks

**Comment by taufik-nurrohman** [comment]
See the source code of custom filter demo &rarr; https://taufik-nurrohman.js.org/tag-picker/tag-picker.f.html

Make your own filter this way:

~~~ .js
picker.f = function(text) {
    return text.toLowerCase().replace(/* your regex pattern to excludes */, '-');
};
~~~

**Comment by jessiemorin** [comment]
Thanks a lot ! Works well !
